pipeline:
  make:
    image: golang
    commands:
      - make clean deps

  hugo:
    image: plugins/hugo
    validate: true

  docker-build-master:
    image: plugins/docker
    secrets: [ docker_username, docker_password ]
    repo: humio/docs
    tags:
      - latest
      - ${DRONE_BRANCH}-${DRONE_BUILD_NUMBER}
    when:
      branch: master

  deploy-master:
    image: e20co/drone-marathon
    server: http://marathon.mesos:8080
    marathonfile: marathon.json
    environment:
      - MARATHON_ID=docs
    values:
      - marathon_id
      - drone_branch
      - drone_build_number
    when:
      branch: master

  deploy-preview:
    image: e20co/drone-marathon
    server: http://marathon.mesos:8080
    marathonfile: marathon.json
    environment:
      - MARATHON_ID=docs-preview
    values:
      - marathon_id
      - drone_branch
      - drone_build_number
    when:
      branch: preview
