---
kind: pipeline
name: default

steps:
- name: make
  image: golang
  commands:
  - make clean deps

- name: hugo
  image: plugins/hugo
  settings:
    hugo_version: "0.55.6"
    validate: true

- name: docker-build-master
  image: plugins/docker
  settings:
    secrets:
    username: cihumio
    password:
      from_secret: docker_password
    repo: humio/docs
    tags:
      - latest
      - ${DRONE_BRANCH}-${DRONE_BUILD_NUMBER}
  when:
    branch: master

- name: deploy-master
  image: plugins/marathon
  settings:
    debug: true
    server: https://marathon.internal.humio.com
    username: drone
    password:
      from_secret: marathon_password
    marathonfile: marathon.json
    values:
      - drone_branch
      - drone_build_number
    when:
      branch: master
