---
kind: pipeline
name: default

steps:
- name: make
  image: golang
  commands:
  - make clean deps

- name: hugo
  image: plugins/hugo
  settings:
    hugo_version: "0.55.6"
    validate: true

- name: docker-build-master
  image: plugins/docker
  settings:
    secrets:
    username: cihumio
    password:
      from_secret: docker_password
    repo: humio/docs
    tags:
      - latest
      - ${DRONE_BRANCH}-${DRONE_BUILD_NUMBER}
  when:
    branch: master

- name: deploy-master
  image: plugins/marathon
  settings:
    debug: true
    server: https://marathon.internal.humio.com
    username: drone
    password:
      from_secret: marathon_password
    id: "/humio/docs"
    docker_image: "humio/docs:${DRONE_BRANCH}-${DRONE_BUILD_NUMBER}"
    cpus: 0.1
    mem: 128
    instances: 2
    docker_port_mappings:
      - container_port: 80
    backoff_factor: 1.15
    docker_force_pull: true
    max_launch_delay_seconds: 3600
    when:
      branch: master
