---
kind: pipeline
name: default

steps:
- name: make
  image: golang
  commands:
  - make clean deps

- name: hugo
  image: plugins/hugo
  settings:
    hugo_version: 0.55.4
    validate: true

- name: docker-build-master
  image: plugins/docker
  settings:
    secrets:
    username: cihumio
    password:
      from_secret: docker_password
    repo: humio/docs
    tags:
      - latest
      - ${DRONE_BRANCH}-${DRONE_BUILD_NUMBER}
  when:
    branch: master

#- name: deploy-master
#  image: e20co/drone-marathon
#  settings:
#    server: http://marathon.mesos:8080
#    marathonfile: marathon.json
#    environment:
#      - MARATHON_ID=docs
#    values:
#      - marathon_id
#      - drone_branch
#      - drone_build_number
#    when:
#      branch: master
