baseURL = "https://docs.humio.com/"
languageCode = "en-us"
title = "Humio documentation"
theme = "hugo-theme-learn"
enableGitInfo = true

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[params]
editURL = "https://github.com/humio/docs.humio.com/edit/master/content/"
description = "Documentation site for Humio"
disableInlineCopyToClipBoard = false
themeVariant = "humio"